---
- name: Install SSM on Ubuntu 16 (In AWS)
  apt:
    deb: "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb"
  when: ansible_distribution == "Ubuntu"

- name: Install SSM on Redhat Family (Amazon Linux, RHEL, and CentOS) (In AWS)
  yum: 
    name: https://s3-us-west-1.amazonaws.com/amazon-ssm-us-west-1/latest/linux_amd64/amazon-ssm-agent.rpm
    state: present
  when: ansible_os_family == "RedHat"

- name: Register and start 
  service: name="amazon-ssm-agent" state="started" enabled="yes"
  
  



    

 